### ISSUE TITLE
When input is cleared, enter no longer works after another selection is made with arrow keys

### ISSUE THREAD

**Issue by fjsj** [wayneashleyberry/selectize-enter-key-submit#1]
Hi, this is a subtle bug, but it causes a bad user experience.  
When you clear the input with backspace, selectize still shows the loaded options and allows you to choose one by selecting with arrow keys and pressing enter. But with your library, the user can't select an option with enter (important: only after the input is cleared and it is still cleared).

For me the solution was to remove the empty `return` in line 10:
https://github.com/wayneashleyberry/selectize-enter-key-submit/blob/ba0831b23f02a0d3089605a3230aa8ba4d6527f6/src/plugin.js#L10

Do you think removing this line could lead to other issues? Thanks for the attention.

**Comment by wayneashleyberry** [comment]
Hey @fjsj, I'll have a look later today. Thanks :)
