### ISSUE TITLE
Publish package on npm

### ISSUE THREAD

**Issue by gijsroge** [wayneashleyberry/selectize-enter-key-submit#3]
Hi, can you publish this please? You have a package.json but have not yet published it, thus many of us cannot use it as we work with yarn/npm to manage our project dependencies.

Thanks

**Comment by wayneashleyberry** [comment]
Most certainly! I'm surprised anyone's using it at all :)

**Comment by wayneashleyberry** [comment]
@gijsroge I've [published to npm](https://www.npmjs.com/package/selectize-enter-key-submit) but now that I think of it... this plugin doesn't actually `export` anything so I'm not sure if that's going to work for you. How do you intend of including this in your application javascript?
